name: restic
base: core18
version: "0.9.6"
summary: Fast, secure, efficient backup program.
description: |
  Restic is a program that does backups right. The design goals are:

  - Easy: Doing backups should be a frictionless process.
  - Fast: Backing up your data with restic should only be limited by your
    network or hard disk bandwidth.
  - Verifiable: Much more important than backup is restore, so restic
    enables you to easily verify that all data can be restored.
  - Secure: Restic uses cryptography to guarantee confidentiality and
    integrity of your data. The location the backup data is stored is
    assumed not to be a trusted environment.
  - Efficient: With the growth of data, additional snapshots should
    only take the storage of the actual increment.
  - Free: restic is free software and licensed under the
    BSD 2-Clause License and actively developed on GitHub.

confinement: classic
grade: stable

parts:
  restic:
    plugin: dump
    source: .
    override-build: |
      chmod +x prep/extractor.sh
      prep/extractor.sh
    organize:
      restic: bin/restic

apps:
  restic:
    command: bin/restic
