name: restic # you probably want to 'snapcraft register <name>'
version: '0.8.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Fast, secure, efficient backup program. # 79 char long summary
description: |
  "Restic is a program that does backups right. The design goals are :
  - Easy: Doing backups should be a frictionless process.
  - Fast: Backing up your data with restic should only be limited by your
  network or hard disk bandwidth.
  - Verifiable: Much more important than backup is restore, so restic
  enables you to easily verify that all data can be restored.
  - Secure: Restic uses cryptography to guarantee confidentiality and
  integrity of your data. The location the backup data is stored is
  assumed not to be a trusted environment.
  - Efficient: With the growth of data, additional snapshots should
  only take the storage of the actual increment.
  - Free: restic is free software and licensed under the
  BSD 2-Clause License and actively developed on GitHub."

confinement: classic # use 'strict' once you have the right plugs and slots
grade: devel

parts:
  restic:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    prepare: |
      chmod +x prep/extractor.sh
      prep/extractor.sh
    organize:
      restic: bin/restic

apps:
  restic:
    command: bin/restic
