name: restic
base: core24
version: "0.18.1"
# https://github.com/snapcore/snapd/blob/master/spdx/licenses.go
license: "BSD-2-Clause"
summary: Fast, secure, efficient backup program.
description: |
  Restic is a program that does backups right. The design goals are:

  - Easy: Doing backups should be a frictionless process.
  - Fast: Backing up your data with restic should only be limited by your
    network or hard disk bandwidth.
  - Verifiable: Much more important than backup is restore, so restic
    enables you to easily verify that all data can be restored.
  - Secure: Restic uses cryptography to guarantee confidentiality and
    integrity of your data. The location the backup data is stored is
    assumed not to be a trusted environment.
  - Efficient: With the growth of data, additional snapshots should
    only take the storage of the actual increment.
  - Free: restic is free software and licensed under the
    BSD 2-Clause License and actively developed on GitHub.

confinement: classic
grade: stable

parts:
  restic:
    plugin: go
    source: https://github.com/restic/restic.git
    source-tag: "v$CRAFT_PROJECT_VERSION"
    build-packages:
      - git
      - golang-go
    override-build: |
      go build -tags selfupdate_off -o restic ./cmd/restic
      mkdir -p $CRAFT_PART_INSTALL/bin
      install -m755 restic $CRAFT_PART_INSTALL/bin/restic
    organize:
      restic: bin/restic

apps:
  restic:
    command: bin/restic
