name: restic
base: core22
version: "0.15.2"
# https://github.com/snapcore/snapd/blob/master/spdx/licenses.go
license: "BSD-2-Clause"
summary: Fast, secure, efficient backup program.
description: |
  Restic is a program that does backups right. The design goals are:

  - Easy: Doing backups should be a frictionless process.
  - Fast: Backing up your data with restic should only be limited by your
    network or hard disk bandwidth.
  - Verifiable: Much more important than backup is restore, so restic
    enables you to easily verify that all data can be restored.
  - Secure: Restic uses cryptography to guarantee confidentiality and
    integrity of your data. The location the backup data is stored is
    assumed not to be a trusted environment.
  - Efficient: With the growth of data, additional snapshots should
    only take the storage of the actual increment.
  - Free: restic is free software and licensed under the
    BSD 2-Clause License and actively developed on GitHub.

confinement: classic
grade: stable
architectures:
  - build-on: amd64
parts:
  restic:
    # Use the nil plugin with wget until bz2 is supported by snapcraft.
    plugin: nil
    build-packages:
      - bzip2
      - wget
    override-pull: |
      wget https://github.com/restic/restic/releases/download/v$SNAPCRAFT_PROJECT_VERSION/$SNAPCRAFT_PROJECT_NAME_$SNAPCRAFT_PROJECT_VERSION_linux_$SNAP_ARCH.bz2
      bunzip2 $SNAPCRAFT_PROJECT_NAME_$SNAPCRAFT_PROJECT_VERSION_linux_$SNAP_ARCH.bz2
    override-build: |
      snapcraftctl build
      install $SNAPCRAFT_PROJECT_NAME_$SNAPCRAFT_PROJECT_VERSION_linux_$SNAP_ARCH $SNAPCRAFT_PART_INSTALL/restic

apps:
  restic:
    command: restic
